# Generated by Django 6.0.2 on 2026-06-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipstech', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dicas',
            new_name='Comentarios',
        ),
        migrations.RenameField(
            model_name='comentarios',
            old_name='descricao',
            new_name='comentado',
        ),
        migrations.RenameField(
            model_name='comentarios',
            old_name='titulo',
            new_name='nome',
        ),
    ]
