# Generated by Django 6.0.2 on 2026-06-17 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipstech', '0002_rename_dicas_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='data_da_postagem',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
