# Generated by Django 6.0.2 on 2026-06-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipstech', '0003_comentarios_data_da_postagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='qtd_likes',
            field=models.IntegerField(default=0),
        ),
    ]
